# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'PLCodeTest' do
  pod 'Alamofire', '~> 2.0'
  pod 'SwiftyJSON', '2.4.0'
end

target 'PLCodeTestTests' do

end

target 'PLCodeTestUITests' do

end

