# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'PLCodeTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PLCodeTest
  pod 'SwiftyJSON'
  pod 'Material', '~> 2.0'
  pod 'TTGSnackbar'

  target 'PLCodeTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PLCodeTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
